[package]
name = "BabySNARKS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
finitefields = "0.1.1"
itertools = "0.12.0"
